export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    SET_MARKER: 'SET_MARKER',
    REMOVE_MARKER: 'REMOVE_MARKER'
}